appId = "0x6c69616e612d7369676e65722d617070"
icon = "resources/.foundation/icon.raw"
publisher = "Foundation Devices, Inc."
description = "Policy-aware Liana signer for Passport Prime"
version = "0.1.0"

[appName]
en = "Liana"

[permissions]
"os/fs" = [
    "AsyncCopyBlock",
    "AsyncRead",
    "AsyncWrite",
    "AtomicCopy",
    "CloseDir",
    "CloseFile",
    "CreateDirMessage",
    "Flush",
    "FlushFs",
    "GetAirlockReadAccess",
    "GetAirlockWriteAccess",
    "GetMetadata",
    "GetUsbReadAccess",
    "GetUsbWriteAccess",
    "GetUserReadAccess",
    "GetUserWriteAccess",
    "MapFileMessage",
    "NextEntry",
    "OpenDirMessage",
    "OpenFileMessage",
    "ReadFile",
    "Remove",
    "Rename",
    "SeekFile",
    "SetLen",
    "SubscribeFilesystemEvent",
    "TruncateFile",
    "WriteFile",
]
"os/gui-server" = [
    "AnimateNextFrame",
    "FinishResponse",
    "GetPendingNavRequest",
    "HideKeyboard",
    "NavigationCancel",
    "RegisterAppMessage",
    "RequestRedraw",
    "ShowModal",
    "SubmitFrame",
    "UpdateKeyboard",
]
"os/security" = ["GetAppSeed"]
"os/settings" = [
    "GetDebugTouch",
    "GetSystemTheme",
    "SubscribeDebugTouch",
    "SubscribeSystemTheme",
]
