// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Router } from "gen/router.slint";
import { Callbacks } from "callbacks.slint";
import { BaseWindow } from "compat/widgets.slint";
import { CurrentTheme, Images, Utils } from "compat/theme.slint";
import { TR } from "compat/tr.slint";

export component AppWindow inherits BaseWindow {
    Router { }
}

export * from "gen/exports.slint";
export { Callbacks, CurrentTheme, Images, TR, Utils }
